### ISSUE TITLE
졸업 요건 정보 데이터 정리

### ISSUE THREAD

**Issue by dojinyou** [Myongji-Graduate/MyongjiGraduate-BE#18]

**Comment by 5uhwann** [comment]
졸업 요건 정보 데이터 정리했습니다. 확인 부탁드립니다.
- 관련 파일 구글드라이브 업로드
- 노션 링크 저장
- ![KakaoTalk_Photo_2022-10-02-18-10-09](https://user-images.githubusercontent.com/106325839/193446888-56fa43e9-7d91-495f-8277-bfe2b6a5fb05.png)

**Comment by dojinyou** [comment]
확인 완료했습니다! 

### 코멘트입니다.
1. `.sql`로 확장자명 변경
2. table별로 sql문 분리하기
3. pk 제약 조건 및 fk 제약조건 걸어주는 `constraint.sql` 별도로 만들기

**Comment by 5uhwann** [comment]
> 

관련 내용 수정해서 구글드라이브에 업로드 했습니다! 확인 부탁드립니다.
