### ISSUE TITLE
전공선택 기준학점 수정 필요

### ISSUE THREAD

**Issue by 5uhwann** [Myongji-Graduate/MyongjiGraduate-BE#42]
현재 전공선택 기준학점이 전공선택과목의 총학점임 -> 졸업요건 전공학점(ex.ICT:70점)에서 전공필수학점을 뺀 학점 으로 변경 필요

**Comment by dojinyou** [comment]
프론트에서 데이터 분기할 때 처리 로직 문제로 프론트에서 처리하는 것으로 이야기 되었습니다!
